# Generated by Django 3.0.2 on 2021-03-27 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('personID', models.AutoField(primary_key=True, serialize=False)),
                ('personName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('politics', models.BooleanField()),
                ('health', models.BooleanField()),
                ('sports', models.BooleanField()),
                ('tech', models.BooleanField()),
                ('message', models.CharField(max_length=240)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('expireDateTime', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=30)),
                ('likeCount', models.IntegerField(default=0)),
                ('dislikeCount', models.IntegerField(default=0)),
                ('commentCount', models.IntegerField(default=0)),
                ('personID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='interaction',
            fields=[
                ('responseID', models.AutoField(primary_key=True, serialize=False)),
                ('response_type', models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike'), ('Comments', 'Comments')], max_length=100)),
                ('comments', models.CharField(max_length=600)),
                ('personID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piazza.person')),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piazza.post')),
            ],
        ),
    ]
